(() => {
  'use strict';
  const KEY='kael-gameplay-maps-v1';
  const ACTIVE='kael-gameplay-active-v1';
  const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
  const blankMap=(name='Novo mapa',size=10)=>({id:uid('map'),name,size,background:null,pins:[],drawing:null});
  const STATUSES=[['normal','Normal'],['voando','Voando'],['preso','Preso'],['lesionado','Lesionado'],['atordoado','Atordoado'],['morto','Morto'],['furioso','Furioso'],['amedrontado','Amedrontado']];
  const STATUS_ICON={normal:'',voando:'↟',preso:'⛓',lesionado:'✚',atordoado:'✦',morto:'☠',furioso:'!',amedrontado:'◈'};
  let state={maps:[],activeId:null};
  let tool='move', drawColor='#e7edf2', drawing=false, last=null, selectedPinId=null;
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.maps))state=x}catch(e){};if(!state.maps.length)state.maps=[blankMap('Mapa 1',10)];state.maps.forEach(m=>m.pins.forEach(p=>{if(!p.status)p.status='normal'}));try{state.activeId=localStorage.getItem(ACTIVE)||state.activeId}catch(e){};if(!state.maps.some(m=>m.id===state.activeId))state.activeId=state.maps[0].id}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(ACTIVE,state.activeId)}catch(e){}}
  const current=()=>state.maps.find(m=>m.id===state.activeId)||state.maps[0];
  function styles(){if(document.getElementById('gameplay-styles'))return;const s=document.createElement('style');s.id='gameplay-styles';s.textContent=`
  .gameplay-wrap{display:grid;gap:14px}.gameplay-top{display:flex;flex-wrap:wrap;gap:8px;align-items:end}.gameplay-top label,.gp-toolbox label{display:grid;gap:4px;font-size:.72rem;color:var(--muted)}.gameplay-top input,.gameplay-top select,.gp-toolbox input,.gp-toolbox select{height:38px;border:1px solid var(--line);border-radius:9px;background:rgba(9,20,31,.92);color:var(--white);padding:0 9px}.gp-btn{height:38px;border:1px solid var(--line);border-radius:9px;background:rgba(16,31,45,.9);color:var(--white);padding:0 12px;font-weight:700;cursor:pointer}.gp-btn.active{background:var(--ice);color:var(--ink)}.gp-btn.danger{color:#ff9d9d;border-color:rgba(255,120,120,.28)}.gp-edit-only{display:none}.editing .gp-edit-only{display:inline-flex}.gp-toolbox{display:flex;flex-wrap:wrap;gap:8px;align-items:end;padding:10px;border:1px solid var(--line);border-radius:12px;background:rgba(7,17,27,.62)}
  .gp-stage-scroll{width:100%;overflow:auto;-webkit-overflow-scrolling:touch;border-radius:14px}.gp-stage{position:relative;width:min(900px,100%);aspect-ratio:1/1;margin:0 auto;background:#101923;background-position:center;background-size:cover;border:1px solid rgba(217,237,245,.25);border-radius:14px;overflow:hidden;touch-action:none;box-shadow:0 14px 40px rgba(0,0,0,.28)}.gp-grid{position:absolute;inset:0;pointer-events:none}.gp-canvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none}.gp-pins{position:absolute;inset:0}.gp-pin{position:absolute;width:42px;height:42px;border-radius:50%;transform:translate(-50%,-50%);display:flex;align-items:center;justify-content:center;background:rgba(9,20,31,.92);border:4px solid #d7edf7;color:white;font-weight:800;font-size:.8rem;box-shadow:0 5px 16px rgba(0,0,0,.42);user-select:none;touch-action:none;cursor:grab}.gp-pin:active{cursor:grabbing}.gp-pin.selected{outline:3px solid var(--gold);outline-offset:4px;z-index:8;filter:drop-shadow(0 0 7px rgba(193,154,91,.55))}.gp-status-badge{position:absolute;right:-8px;top:-9px;min-width:20px;height:20px;padding:0 4px;border-radius:10px;background:#111923;border:1px solid rgba(255,255,255,.32);display:flex;align-items:center;justify-content:center;font-size:.63rem;font-weight:900;color:#fff;box-shadow:0 2px 7px rgba(0,0,0,.45)}.gp-pin[data-status="morto"]{opacity:.6;filter:grayscale(.9)}.gp-pin[data-status="morto"].selected{filter:grayscale(.9) drop-shadow(0 0 7px rgba(193,154,91,.55))}.gp-pin[data-status="furioso"]{box-shadow:0 0 0 3px rgba(255,80,80,.16),0 5px 16px rgba(0,0,0,.42)}.gp-pin[data-status="amedrontado"]{box-shadow:0 0 0 3px rgba(150,120,255,.18),0 5px 16px rgba(0,0,0,.42)}.gp-pin[data-status="voando"]{transform:translate(-50%,-58%);box-shadow:0 10px 18px rgba(0,0,0,.48)}.gp-map-empty{padding:30px;text-align:center;color:var(--muted)}
  .gp-pin-editor{display:grid;grid-template-columns:minmax(120px,1fr) 118px minmax(135px,.8fr) auto;gap:8px;padding:10px;border:1px solid var(--line);border-radius:11px;background:rgba(7,17,27,.48);transition:border-color .18s,background .18s,box-shadow .18s}.gp-pin-editor.selected{border-color:var(--gold);background:rgba(193,154,91,.11);box-shadow:0 0 0 2px rgba(193,154,91,.18),0 7px 20px rgba(0,0,0,.22)}.gp-pin-editor input,.gp-pin-editor select{height:38px;border:1px solid var(--line);border-radius:8px;background:rgba(9,20,31,.92);color:white;padding:0 9px}.gp-pin-editor input[type=color]{padding:3px}.gp-help{font-size:.8rem;color:var(--muted);line-height:1.45}.gp-bg-name{font-size:.75rem;color:var(--muted)}
  @media(max-width:760px){.gp-stage{width:100%;min-width:0}.gp-pin{width:36px;height:36px;border-width:3px;font-size:.72rem}.gp-pin-editor{grid-template-columns:1fr 82px}.gp-pin-editor select{grid-column:1}.gp-pin-editor .gp-btn{grid-column:2}.gameplay-top>*{flex:1 1 120px}.gameplay-top .gp-btn{flex:0 0 auto}.gp-toolbox>*{flex:1 1 90px}}
  `;document.head.appendChild(s)}
  function installTab(){const nav=document.querySelector('.tabnav'),shell=document.querySelector('main.shell');if(!nav||!shell||document.querySelector('[data-tab="gameplay"]'))return false;const b=document.createElement('button');b.className='tab-btn';b.type='button';b.dataset.tab='gameplay';b.textContent='Gameplay';nav.appendChild(b);const sec=document.createElement('section');sec.id='tab-gameplay';sec.className='tab-panel';sec.innerHTML=`<div class="card"><div class="card-head"><span class="card-icon-badge">⚔</span><div class="card-head-text"><h2>Gameplay</h2><p class="hint">Demonstração tática para visualizar posições, movimentação e situações de mapa.</p></div></div><div id="gameplayApp" class="gameplay-wrap"></div></div>`;shell.appendChild(sec);b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');sec.classList.add('active');render();window.scrollTo({top:0,behavior:'smooth'})});return true}
  function gridBackground(n){return `linear-gradient(to right,rgba(217,237,245,.22) 1px,transparent 1px),linear-gradient(to bottom,rgba(217,237,245,.22) 1px,transparent 1px)`}
  function render(){const root=document.getElementById('gameplayApp');if(!root)return;const m=current();if(selectedPinId&&!m.pins.some(p=>p.id===selectedPinId))selectedPinId=null;root.innerHTML=`
   <div class="gameplay-top"><label>Mapa<select id="gpMapSelect">${state.maps.map(x=>`<option value="${x.id}" ${x.id===m.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><button class="gp-btn" id="gpAddMap">+ Novo mapa</button><button class="gp-btn danger" id="gpDeleteMap">Excluir mapa</button><label>Nome<input id="gpMapName" value="${esc(m.name)}"></label><label>Grade X × X<input id="gpSize" type="number" min="2" max="40" value="${m.size}"></label><button class="gp-btn gp-edit-only" id="gpBgBtn">Background</button><button class="gp-btn gp-edit-only" id="gpBgClear">Remover fundo</button><input id="gpBgFile" type="file" accept="image/*" hidden><span class="gp-bg-name">${m.background?'Background ativo':'Sem background'}</span></div>
   <div class="gp-toolbox"><button class="gp-btn ${tool==='move'?'active':''}" data-tool="move">Mover pins</button><button class="gp-btn ${tool==='draw'?'active':''}" data-tool="draw">✎ Lápis</button><button class="gp-btn ${tool==='erase'?'active':''}" data-tool="erase">⌫ Borracha</button><label>Cor do lápis<input id="gpDrawColor" type="color" value="${drawColor}"></label><button class="gp-btn" id="gpClearDrawing">Limpar desenho</button><button class="gp-btn" id="gpAddPin">+ Pin</button></div>
   <div class="gp-stage-scroll"><div class="gp-stage" id="gpStage" style="${m.background?`background-image:url('${m.background}')`:''}"><div class="gp-grid" style="background-image:${gridBackground(m.size)};background-size:${100/m.size}% ${100/m.size}%;"></div><canvas class="gp-canvas" id="gpCanvas"></canvas><div class="gp-pins" id="gpPins"></div></div></div><div id="gpPinList"></div><p class="gp-help">Toque em um pin para destacar seu item na lista de edição. Arraste no modo “Mover pins”. Status, posição, desenho e background ficam salvos neste dispositivo.</p>`;bindControls();setupCanvas();renderPins();renderPinList()}
  function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function selectPin(id,scroll=true){selectedPinId=id;document.querySelectorAll('.gp-pin').forEach(x=>x.classList.toggle('selected',x.dataset.pin===id));document.querySelectorAll('.gp-pin-editor').forEach(x=>x.classList.toggle('selected',x.dataset.pinEditor===id));const row=document.querySelector(`.gp-pin-editor[data-pin-editor="${id}"]`);if(scroll&&row)row.scrollIntoView({behavior:'smooth',block:'center'})}
  function bindControls(){const m=current();document.getElementById('gpMapSelect').onchange=e=>{selectedPinId=null;state.activeId=e.target.value;save();render()};document.getElementById('gpAddMap').onclick=()=>{selectedPinId=null;const n=blankMap(`Mapa ${state.maps.length+1}`,10);state.maps.push(n);state.activeId=n.id;save();render()};document.getElementById('gpDeleteMap').onclick=()=>{selectedPinId=null;if(state.maps.length===1){state.maps=[blankMap('Mapa 1',10)];state.activeId=state.maps[0].id}else{state.maps=state.maps.filter(x=>x.id!==m.id);state.activeId=state.maps[0].id}save();render()};document.getElementById('gpMapName').onchange=e=>{m.name=e.target.value.trim()||'Mapa sem nome';save();render()};document.getElementById('gpSize').onchange=e=>{m.size=Math.max(2,Math.min(40,Number(e.target.value)||10));save();render()};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;render()});document.getElementById('gpDrawColor').oninput=e=>drawColor=e.target.value;document.getElementById('gpClearDrawing').onclick=()=>{m.drawing=null;save();render()};document.getElementById('gpAddPin').onclick=()=>{const p={id:uid('pin'),label:'K',x:.5,y:.5,color:'#d7edf7',status:'normal'};m.pins.push(p);selectedPinId=p.id;save();renderPins();renderPinList();selectPin(p.id,true)};const f=document.getElementById('gpBgFile');document.getElementById('gpBgBtn').onclick=()=>f.click();document.getElementById('gpBgClear').onclick=()=>{m.background=null;save();render()};f.onchange=async()=>{if(!f.files[0])return;m.background=await resize(f.files[0],1400,.8);save();render()}}
  function resize(file,max=1400,q=.82){return new Promise((res,rej)=>{const r=new FileReader;r.onerror=rej;r.onload=()=>{const im=new Image;im.onerror=rej;im.onload=()=>{let w=im.width,h=im.height;if(w>max||h>max){if(w>h){h=Math.round(h*max/w);w=max}else{w=Math.round(w*max/h);h=max}}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);res(c.toDataURL('image/webp',q))};im.src=r.result};r.readAsDataURL(file)})}
  function renderPins(){const box=document.getElementById('gpPins');if(!box)return;const m=current();box.innerHTML=m.pins.map(p=>`<div class="gp-pin ${p.id===selectedPinId?'selected':''}" data-pin="${p.id}" data-status="${esc(p.status||'normal')}" title="${esc(STATUSES.find(s=>s[0]===(p.status||'normal'))?.[1]||'Normal')}" style="left:${p.x*100}%;top:${p.y*100}%;border-color:${p.color}">${esc(p.label||'?')}${p.status&&p.status!=='normal'?`<span class="gp-status-badge">${STATUS_ICON[p.status]||'•'}</span>`:''}</div>`).join('');box.querySelectorAll('.gp-pin').forEach(el=>{const p=m.pins.find(x=>x.id===el.dataset.pin);let dragging=false,moved=false;const move=e=>{if(!dragging||tool!=='move')return;e.preventDefault();moved=true;const r=box.getBoundingClientRect();p.x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));p.y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));el.style.left=p.x*100+'%';el.style.top=p.y*100+'%'};const end=()=>{if(dragging){dragging=false;save();if(!moved)selectPin(p.id,true)}};el.addEventListener('pointerdown',e=>{if(tool!=='move')return;dragging=true;moved=false;el.setPointerCapture?.(e.pointerId)});el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('click',()=>{if(tool==='move'&&!moved)selectPin(p.id,true)})})}
  function renderPinList(){const root=document.getElementById('gpPinList');if(!root)return;const m=current();root.innerHTML=m.pins.length?m.pins.map(p=>`<div class="gp-pin-editor ${p.id===selectedPinId?'selected':''}" data-pin-editor="${p.id}"><input data-pin-label="${p.id}" value="${esc(p.label)}" placeholder="Iniciais"><input data-pin-color="${p.id}" type="color" value="${p.color}" title="Cor da borda"><select data-pin-status="${p.id}" aria-label="Status do pin">${STATUSES.map(s=>`<option value="${s[0]}" ${s[0]===(p.status||'normal')?'selected':''}>${s[1]}</option>`).join('')}</select><button class="gp-btn danger" data-pin-del="${p.id}">Excluir</button></div>`).join(''):'<div class="gp-map-empty">Nenhum pin neste mapa.</div>';root.querySelectorAll('.gp-pin-editor').forEach(r=>r.onclick=e=>{if(!e.target.closest('button'))selectPin(r.dataset.pinEditor,false)});root.querySelectorAll('[data-pin-label]').forEach(i=>i.oninput=()=>{const p=m.pins.find(x=>x.id===i.dataset.pinLabel);p.label=i.value.slice(0,5);save();renderPins()});root.querySelectorAll('[data-pin-color]').forEach(i=>i.oninput=()=>{const p=m.pins.find(x=>x.id===i.dataset.pinColor);p.color=i.value;save();renderPins()});root.querySelectorAll('[data-pin-status]').forEach(i=>i.onchange=()=>{const p=m.pins.find(x=>x.id===i.dataset.pinStatus);p.status=i.value;save();renderPins();selectPin(p.id,false)});root.querySelectorAll('[data-pin-del]').forEach(b=>b.onclick=()=>{if(selectedPinId===b.dataset.pinDel)selectedPinId=null;m.pins=m.pins.filter(x=>x.id!==b.dataset.pinDel);save();renderPins();renderPinList()})}
  function setupCanvas(){const c=document.getElementById('gpCanvas'),stage=document.getElementById('gpStage');if(!c||!stage)return;const m=current();const size=()=>{const r=stage.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);if(m.drawing){const im=new Image;im.onload=()=>ctx.drawImage(im,0,0,r.width,r.height);im.src=m.drawing}};size();const pos=e=>{const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};c.onpointerdown=e=>{if(tool==='move')return;drawing=true;last=pos(e);c.setPointerCapture?.(e.pointerId)};c.onpointermove=e=>{if(!drawing||tool==='move')return;e.preventDefault();const q=pos(e),ctx=c.getContext('2d');ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=tool==='erase'?22:4;if(tool==='erase'){ctx.globalCompositeOperation='destination-out';ctx.strokeStyle='rgba(0,0,0,1)'}else{ctx.globalCompositeOperation='source-over';ctx.strokeStyle=drawColor}ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.restore();last=q};const end=()=>{if(!drawing)return;drawing=false;try{m.drawing=c.toDataURL('image/png');save()}catch(e){}};c.onpointerup=end;c.onpointercancel=end}
  function init(){load();styles();installTab();render()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();