const CACHE_NAME = "kael-app-v7";
const PRECACHE_URLS = ["./","./index.html","./styles.css","./app.js","./manifest.webmanifest","./assets/kael-portrait.webp","./assets/bg-winterfell.jpg","./assets/weapon-presa-de-lofurin.webp","./assets/shield-lobo-branco.webp","./assets/armor-escamas.webp","./icons/icon-192.png","./icons/icon-512.png","./icons/icon-maskable-192.png","./icons/icon-maskable-512.png","./icons/favicon.png"];

const UI_PATCH = `
;(() => {
 const KEY='kael-character-images';
 let imgs={}; try{imgs=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){}
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(imgs))}catch(e){}};
 const styles=()=>{if(document.getElementById('kael-v7'))return;const s=document.createElement('style');s.id='kael-v7';s.textContent=\`
 .notes-card textarea#gameNotes{overflow-y:hidden!important;resize:none!important}
 #dynamicPeopleGrid.people-grid,#dynamicPeopleGrid.dynamic-people{display:flex!important;flex-direction:column!important;grid-template-columns:none!important;gap:0!important;width:100%!important}
 #dynamicPeopleGrid .person{width:100%!important;max-width:none!important;margin:0!important;padding:20px 0!important;border:0!important;border-bottom:1px solid rgba(193,154,91,.22)!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}
 #dynamicPeopleGrid .person:last-child{border-bottom:0!important}
 #dynamicPeopleGrid .person-fields{display:grid!important;grid-template-columns:140px minmax(220px,1fr) minmax(180px,.65fr)!important;gap:10px 12px!important;width:100%!important;align-items:start}
 .char-photo{grid-row:1/3;width:140px;height:170px;border:1px dashed rgba(193,154,91,.45);border-radius:12px;overflow:hidden;background:rgba(4,13,22,.55);display:flex;align-items:center;justify-content:center;position:relative}
 .char-photo img{width:100%;height:100%;object-fit:cover;display:block}.char-photo.empty img{display:none}.char-photo-placeholder{text-align:center;padding:12px;color:var(--muted);font-size:.78rem;line-height:1.35}.char-photo:not(.empty) .char-photo-placeholder{display:none}
 .char-photo-actions{position:absolute;left:6px;right:6px;bottom:6px;display:flex;gap:5px;opacity:0;transition:.2s}.editing .char-photo-actions{opacity:1}.char-photo-actions button{flex:1;padding:6px 5px;font-size:.68rem;border-radius:7px;border:1px solid rgba(255,255,255,.2);background:rgba(4,13,22,.88);color:#fff}.char-photo-actions .remove{color:#ff9a9a}
 #dynamicPeopleGrid [data-person-key=name]{grid-column:2!important;font-size:1.05rem!important;font-weight:700!important}#dynamicPeopleGrid [data-person-key=role]{grid-column:3!important}
 #dynamicPeopleGrid textarea[data-person-key=description]{grid-column:2/-1!important;width:100%!important;min-height:170px!important;line-height:1.55!important;resize:vertical!important}.person-remove{z-index:4!important}
 @media(max-width:760px){#dynamicPeopleGrid .person-fields{grid-template-columns:96px 1fr!important}.char-photo{width:96px;height:122px;grid-column:1!important;grid-row:1/3!important}#dynamicPeopleGrid [data-person-key=name],#dynamicPeopleGrid [data-person-key=role]{grid-column:2!important}#dynamicPeopleGrid textarea[data-person-key=description]{grid-column:1/-1!important;min-height:190px!important}.char-photo-actions{opacity:1;flex-direction:column}.char-photo-actions button{font-size:.6rem;padding:4px 2px}}
 \`;document.head.appendChild(s)};
 const fitNotes=()=>{const n=document.getElementById('gameNotes');if(!n)return;n.style.overflowY='hidden';n.style.resize='none';n.style.height='auto';n.style.height=Math.max(n.scrollHeight,Math.round(innerHeight*(innerWidth<=760?.64:.58)))+'px';if(!n.dataset.ag){n.dataset.ag='1';n.addEventListener('input',fitNotes)}};
 const renameHeading=()=>{document.querySelectorAll('#tab-historia h2').forEach(h=>{if(h.textContent.trim()==='Personagens do background')h.textContent='Personagens'})};
 const resizeImage=(file)=>new Promise((res,rej)=>{const r=new FileReader;r.onerror=rej;r.onload=()=>{const im=new Image;im.onerror=rej;im.onload=()=>{let w=im.width,h=im.height,m=700;if(w>m||h>m){if(w>h){h=Math.round(h*m/w);w=m}else{w=Math.round(w*m/h);h=m}}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);res(c.toDataURL('image/webp',.82))};im.src=r.result};r.readAsDataURL(file)});
 const enhance=()=>{const g=document.getElementById('dynamicPeopleGrid');if(!g)return;g.querySelectorAll('.person').forEach(p=>{const id=p.dataset.personId;if(!id||p.querySelector('.char-photo'))return;const fields=p.querySelector('.person-fields');if(!fields)return;const box=document.createElement('div');box.className='char-photo '+(imgs[id]?'':'empty');box.innerHTML='<img alt="Imagem do personagem"><div class="char-photo-placeholder">Imagem<br>opcional</div><div class="char-photo-actions"><button type="button" class="choose">Imagem</button><button type="button" class="remove">×</button></div><input type="file" accept="image/*" hidden>';if(imgs[id])box.querySelector('img').src=imgs[id];const input=box.querySelector('input');box.querySelector('.choose').onclick=()=>input.click();input.onchange=async()=>{if(!input.files[0])return;imgs[id]=await resizeImage(input.files[0]);save();box.querySelector('img').src=imgs[id];box.classList.remove('empty')};box.querySelector('.remove').onclick=()=>{delete imgs[id];save();box.querySelector('img').removeAttribute('src');box.classList.add('empty')};fields.prepend(box)});g.querySelectorAll('textarea[data-person-key=description]').forEach(a=>a.setAttribute('rows',innerWidth<=760?'8':'7'))};
 const apply=()=>{styles();renameHeading();fitNotes();enhance()};apply();new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});setTimeout(apply,100);setTimeout(apply,500);addEventListener('resize',apply);
})();`;
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(PRECACHE_URLS)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE_NAME).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.pathname.endsWith("/app.js")){e.respondWith(caches.match(e.request).then(async cached=>{let r=cached;if(!r){try{r=await fetch(e.request);if(r&&r.ok&&r.type==="basic"){const cl=r.clone();caches.open(CACHE_NAME).then(c=>c.put(e.request,cl))}}catch(_){}}if(!r)return new Response("",{status:503});const src=await r.clone().text();return new Response(src+UI_PATCH,{status:r.status,statusText:r.statusText,headers:{"Content-Type":"application/javascript; charset=utf-8","Cache-Control":"no-cache"}})}));return}e.respondWith(caches.match(e.request).then(cached=>cached||fetch(e.request).then(r=>{if(r&&r.ok&&r.type==="basic"){const cl=r.clone();caches.open(CACHE_NAME).then(c=>c.put(e.request,cl))}return r}).catch(()=>cached))) });